apiVersion: v1
kind: Service
metadata:
    name: gateway
    labels:
        app: gateway
spec:
# PARA A AWS ENTENDER E MONTAR O LOADBALANCER
    type: LoadBalancer
    ports:
        - port: 8080
    selector:
        app: gateway